services:
  waf:
    build: ./waf
    container_name: waf
    restart: unless-stopped
    ports: ["80:8080"]      # 컨테이너는 비루트 사용자라 기본 8080/8443 리슨
    environment:
      TZ: Asia/Seoul
      BACKEND: http://web:80         # 필수. 리버스 프록시 대상
      ERRORLOG: /var/log/nginx/error.log
      MODSEC_AUDIT_LOG: /var/log/modsecurity/audit.log
      MODSEC_AUDIT_LOG_FORMAT: Native
      # CRS 주요 스위치들
      BLOCKING_PARANOIA: "2"
      DETECTION_PARANOIA: "2"
      ANOMALY_INBOUND: "10"
      ANOMALY_OUTBOUND: "5"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./logs/modsecurity:/var/log/modsecurity
    tmpfs:
      - /tmp:rw,mode=1777
      - /var/cache/nginx:rw,mode=1777
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - web
    networks:
      - shared

  web:
    image: nginx:alpine
    container_name: web
    command: sh -c "echo 'OK' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks: [shared]

networks:
  shared:
    driver: bridge
