services:
  crs-nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    hostname: waf
    restart: always
    environment:
      TZ: Asia/Seoul
      BACKEND: http://web:80  # 프록시 대상
      ERRORLOG: /var/log/nginx/error.log
      MODSEC_AUDIT_LOG: /var/log/modsecurity/audit.log
      MODSEC_AUDIT_LOG_FORMAT: Native
      MODSEC_AUDIT_ENGINE: DetectionOnly  #  오탐/튜닝 → 그다음 차단까지 하려면 On
    ports:
      - "80:8080"

    volumes:
      - ./modsec-logs:/var/log/modsecurity
      - ./docker/modsecurity/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./docker/modsecurity/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    networks:
      - shared_network
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  web:
    image: nginx:alpine
    container_name: web
    command: sh -c "echo 'OK' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
