spring:
  application:
    name: waf-console-backend

  datasource:
    url: jdbc:mysql://localhost:3306/waf?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1108Qkrgks!!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # ← validate에서 변경 (개발 단계)
    show-sql: true          # ← 디버깅용 true로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: false          # ← Flyway 비활성화
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-client-secret}
            scope: openid,profile,email

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    dev.waf.console: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always

waf:
  console:
    security:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        allow-credentials: true
    simulation:
      timeout-seconds: 300
      max-concurrent-runs: 10
    report:
      screenshot:
        timeout-seconds: 30
        window-width: 1920
        window-height: 1080
      pdf:
        template-path: classpath:templates/report